// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)

import GalleryController from "./gallery_controller"
application.register("gallery", GalleryController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import IconController from "./icon_controller"
application.register("icon", IconController)

import MapController from "./map_controller"
application.register("map", MapController)

import MaterialsToggleController from "./materials_toggle_controller"
application.register("materials-toggle", MaterialsToggleController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import NavlistController from "./navlist_controller"
application.register("navlist", NavlistController)

import RequirementController from "./requirement_controller"
application.register("requirement", RequirementController)

import TypedJsController from "./typed_js_controller"
application.register("typed-js", TypedJsController)
